name: Upload to GCS
on:
  push:
    branches:
      - main  # Triggers on push to main branch
  pull_request:
    branches:
      - main
jobs:
  upload-to-gcs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: twilight-mlops-poc  # Project ID
        service_account_key: ${{ secrets.MLOPS_KEY }}  # Secret containing the service account JSON key
        export_default_credentials: true
    - name: Upload Code to GCS
      env:
        GCS_BUCKET: gitmlopscode  # Your GCS bucket name
      run: |
        # Upload all files in the repository to the specified GCS bucket
        gsutil -m rsync -r . "gs://${GCS_BUCKET}/project-code/"