name: Docker Build and Push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Docker Buildx (required for building images)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: Build and tag the Docker image
    - name: Build and tag Docker image
      run: |
        docker build -t aiml .
        docker tag aiml:latest naveenyogi/nodeapp:aiml
    # Step 5: Push the image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: |
        docker push naveenyogi/nodeapp:aiml
