name: Model Retraining and Deployment Pipeline

on:
  push:
    paths:
      - "data/**"           # Trigger on changes in the data/ folder
      - "src/**"            # Trigger on changes in the src/ folder
      - "requirements.txt"  # Trigger on dependency updates

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Train the base model
    - name: Train Model
      run: |
        python src/train_model.py

    # Step 5: Hyperparameter Tuning
    - name: Hyperparameter Tuning
      run: |
        python src/hyperparameter_tuning.py

    # Step 6: Model Evaluation
    - name: Evaluate Model
      run: |
        python src/evaluate_model.py

    # Step 7: Deploy the new model if it performs better
    - name: Deploy Model if New Model is Better
      if: success()
      run: |
        python src/deploy_model.py

    # Step 8: Upload the best model as an artifact for backup
    - name: Upload Model Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: latest_model
        path: models/previous_model.joblib
